# Generated by Django 2.0 on 2018-12-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testAlarm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filegz', models.FileField(upload_to='gzs/%Y/%m/%d')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
