# Generated by Django 2.0 on 2019-01-02 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testAlarm', '0002_uploadfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
