# Generated by Django 2.0 on 2019-01-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testAlarm', '0003_delete_uploadfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileGz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gz', models.FileField(upload_to='GzFile/%Y/%m/%d')),
                ('GzName', models.CharField(max_length=64)),
            ],
        ),
    ]
